baseurl         = "https://vanderLaan.github.io/tlbbd-sp2018/"
theme           = "sp-minimal"
languageCode    = "en-us"
title           = "PH290 - TLBBD"
disqusShortname = ""
paginate        = 5

[params]
  title       = "PH 290 - TLBBD"
  subtitle    = "Targeted Learning in Biomedical Big Data"
  copyright   = "Released under the MIT license."
  authorImage = "logo-tl.jpeg"

  #"single" or "multi"
  renderType = "multi"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = ""

  name = "Mark van der Laan, Nima Hejazi, Wilson Cai, David Benkeser"
  description = "Welcome to the course website for Targeted Learning in Biomedical Big Data at UC Berkeley (Spring 2018)"
  pageNotFoundTitle = "404 - Page not found"

